[package]
name = "gn-deps"
version = "0.1.0"
authors = ["Taylor Cramer <cramertj@google.com>"]

[dependencies]
failure = "0.1.1"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
toml = "0.4.5"
