[package]
name = "garnet_public_lib_network_fidl"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Rob Tsuk <robtsuk@google.com>"]
description = "Generated interface"
repository = "https://fuchsia.googlesource.com/garnet/"

[dependencies]
fidl = "0.1.0"
fuchsia-zircon = "0.3.2"
futures = "0.1.15"
tokio-core = "0.1"
tokio-fuchsia = "0.1.0"
