[package]
name = "tokio-fuchsia"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Tristan Hume <trishume@google.com>"]
repository = "https://fuchsia.googlesource.com/tokio-fuchsia/"

[dependencies]
bytes = "0.4"
futures = "0.1"
mio = "= 0.6.10"
tokio-core = "= 0.1.10"
tokio-io = "0.1"
fuchsia-zircon = "= 0.3.1"
