[package]
name = "fuchsia-llui"
version = "0.1.0"
authors = ["Rob Tsuk <robtsuk@google.com>"]

[dependencies]
fdio = { path = '../fdio' }
font-rs = { git = "https://github.com/google/font-rs.git" }
fuchsia-zircon-sys = { path = "../fuchsia-zircon/fuchsia-zircon-sys" }

[dependencies.error-chain]
version = "0.11.0"
default-features = false
